name: CI Github Actions

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

env:
  DEFAULT_PYTHON_VERSION: '3.7'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }} 🐍
      uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Read Poetry Version 🔢
      run: |
        echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
      shell: bash

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Load Poetry Cached Libraries ⬇
      id: cache-poetry
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ env.DEFAULT_PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ secrets.POETRY_CACHE_VERSION }}
        restore-keys: ${{ runner.os }}-poetry-${{ env.DEFAULT_PYTHON_VERSION }}

    - name: Clear Poetry cache
      if: steps.cache-poetry.outputs.cache-hit == 'true' && contains(github.event.pull_request.labels.*.name, 'tools:clear-poetry-cache-unit-tests')
      run: rm -r .venv

    - name: Create virtual environment
      if: (steps.cache-poetry.outputs.cache-hit != 'true' || contains(github.event.pull_request.labels.*.name, 'tools:clear-poetry-cache-unit-tests'))
      run: python -m venv create .venv

    - name: Set up virtual environment
      run: poetry config virtualenvs.in-project true

    - name: Install Dependencies 📦
      run: |
        make install

    - name: Lint Code 🎎
      run: |
        poetry run flake8 .github/scripts --extend-ignore D
        poetry run black --check .github/scripts

    - name: Test Code 🔍
      run: |
        make test-gh-actions
